### ISSUE TITLE
This is actually a request more than a issue. Can you do that the extension works also with the Opera GX dezzer player?

### ISSUE THREAD

**Issue by Rus3r** [AdrienC/discord-deezer-chrome#4]

**Comment by Rus3r** [comment]
![image](https://user-images.githubusercontent.com/88398430/157264830-e9876949-b651-4aec-a63d-46baa2935883.png)

**Comment by hans-juergen** [comment]
Do you mean the new sidebar player which is also available in the normal Opera version now? If you only want to install the Discord extension in Opera (GX or standard version) the usual way, you can use the Chrome version for that which you might already know. It also works in Edge, by the way, as it can also use Chrome extensions now.

**Comment by Rus3r** [comment]
> Do you mean the new sidebar player which is also available in the normal Opera version now? If you only want to install the Discord extension in Opera (GX or standard version) the usual way, you can use the Chrome version for that which you might already know. It also works in Edge, by the way, as it can also use Chrome extensions now.

the sidebar player, I tried it with the chrome version
